# Generated by Django 5.0.6 on 2026-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='pending_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationotp',
            name='pending_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationotp',
            name='pending_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
